// Generates public/icons.svg: one <symbol> per icon, referenced everywhere as
// <svg class="ico"><use href="/icons.svg#name"/></svg>. The name list lives
// in public/public.js (UI_ICON_NAMES) so the runtime catalog and the sprite
// cannot drift; geometry comes verbatim from lucide-static (ISC) plus the
// multicolour Google "G" brand mark.
//
//   npm run icons

import { readFile, writeFile } from "node:fs/promises";

const root = new URL("../", import.meta.url);
const publicJs = await readFile(new URL("public/public.js", root), "utf8");
const listSource = publicJs.match(/const UI_ICON_NAMES = new Set\(\[([\s\S]*?)\]\);/)?.[1];
if (!listSource) throw new Error("UI_ICON_NAMES not found in public/public.js");
const names = [...listSource.matchAll(/"([a-z0-9-]+)"/g)].map((m) => m[1]);

// Brand marks and anything Lucide does not ship.
const CUSTOM = {
  "google-g": `<path stroke="none" fill="#4285F4" d="M23.5 12.27c0-.79-.07-1.54-.2-2.27H12v4.3h6.46a5.53 5.53 0 0 1-2.4 3.62v3h3.87c2.27-2.09 3.57-5.17 3.57-8.65z"/><path stroke="none" fill="#34A853" d="M12 24c3.24 0 5.95-1.07 7.93-2.9l-3.87-3c-1.07.72-2.45 1.15-4.06 1.15-3.12 0-5.77-2.11-6.71-4.94H1.29v3.1A12 12 0 0 0 12 24z"/><path stroke="none" fill="#FBBC05" d="M5.29 14.31A7.2 7.2 0 0 1 4.91 12c0-.8.14-1.58.38-2.31V6.6H1.29A12 12 0 0 0 0 12c0 1.94.46 3.77 1.29 5.4l4-3.09z"/><path stroke="none" fill="#EA4335" d="M12 4.75c1.76 0 3.34.61 4.59 1.8l3.44-3.44C17.94 1.19 15.24 0 12 0A12 12 0 0 0 1.29 6.6l4 3.09C6.23 6.86 8.88 4.75 12 4.75z"/>`,
};

const symbols = [];
for (const name of names) {
  if (CUSTOM[name]) {
    symbols.push(`<symbol id="${name}" viewBox="0 0 24 24">${CUSTOM[name]}</symbol>`);
    continue;
  }
  let svg;
  try {
    svg = await readFile(new URL(`node_modules/lucide-static/icons/${name}.svg`, root), "utf8");
  } catch {
    throw new Error(`No Lucide icon named "${name}" (check public/public.js UI_ICON_NAMES)`);
  }
  const body = svg
    .replace(/<!--[\s\S]*?-->/g, "")
    .replace(/^[\s\S]*?<svg[^>]*>/, "")
    .replace(/<\/svg>[\s\S]*$/, "")
    .replace(/\s+/g, " ")
    .replace(/> </g, "><")
    .trim();
  symbols.push(`<symbol id="${name}" viewBox="0 0 24 24">${body}</symbol>`);
}

const out = `<svg xmlns="http://www.w3.org/2000/svg"><!-- generated by scripts/build-icons.mjs; Lucide icons (ISC) --><defs>${symbols.join("")}</defs></svg>\n`;
await writeFile(new URL("public/icons.svg", root), out);
console.log(`icons.svg: ${names.length} symbols, ${(out.length / 1024).toFixed(1)} KiB`);
